function register_stairsplus_alias(subname)
minetest.register_alias("stairsplus:slab_" .. subname, "moreblocks:slab_" .. subname)
minetest.register_alias("stairsplus:slab_" .. subname .. "_inverted", "moreblocks:slab_" .. subname .. "_inverted")
minetest.register_alias("stairsplus:slab_" .. subname .. "_wall", "moreblocks:slab_" .. subname .. "_wall")
minetest.register_alias("stairsplus:stair_" .. subname, "moreblocks:stair_" .. subname)
minetest.register_alias("stairsplus:stair_" .. subname .. "_inverted", "moreblocks:stair_" .. subname .. "_inverted")
minetest.register_alias("stairsplus:stair_" .. subname .. "_wall", "moreblocks:stair_" .. subname .. "_wall")
minetest.register_alias("stairsplus:stair_" .. subname .. "_wall_half", "moreblocks:stair_" .. subname .. "_wall_half")
minetest.register_alias("stairsplus:stair_" .. subname .. "_wall_half_inverted", "moreblocks:stair_" .. subname .. "_wall_half_inverted")
minetest.register_alias("stairsplus:stair_" .. subname .. "_half", "moreblocks:stair_" .. subname .. "_half")
minetest.register_alias("stairsplus:stair_" .. subname .. "_half_inverted", "moreblocks:stair_" .. subname .. "_half_inverted")
minetest.register_alias("stairsplus:stair_" .. subname .. "_right_half", "moreblocks:stair_" .. subname .. "_right_half")
minetest.register_alias("stairsplus:stair_" .. subname .. "_right_half_inverted", "moreblocks:stair_" .. subname .. "_right_half_inverted")
minetest.register_alias("stairsplus:stair_" .. subname .. "_wall_half", "moreblocks:stair_" .. subname .. "_wall_half")
minetest.register_alias("stairsplus:stair_" .. subname .. "_wall_half_inverted", "moreblocks:stair_" .. subname .. "_wall_half_inverted")
minetest.register_alias("stairsplus:stair_" .. subname .. "_inner", "moreblocks:stair_" .. subname .. "_inner")
minetest.register_alias("stairsplus:stair_" .. subname .. "_inner_inverted", "moreblocks:stair_" .. subname .. "_inner_inverted")
minetest.register_alias("stairsplus:stair_" .. subname .. "_outer", "moreblocks:stair_" .. subname .. "_outer")
minetest.register_alias("stairsplus:stair_" .. subname .. "_outer_inverted", "moreblocks:stair_" .. subname .. "_outer_inverted")
minetest.register_alias("stairsplus:panel_" .. subname .. "_bottom", "moreblocks:panel_" .. subname .. "_bottom")
minetest.register_alias("stairsplus:panel_" .. subname .. "_top", "moreblocks:panel_" .. subname .. "_top")
minetest.register_alias("stairsplus:panel_" .. subname .. "_vertical", "moreblocks:panel_" .. subname .. "_vertical")
minetest.register_alias("stairsplus:micro_" .. subname .. "_bottom", "moreblocks:micro_" .. subname .. "_bottom")
minetest.register_alias("stairsplus:micro_" .. subname .. "_top", "moreblocks:micro_" .. subname .. "_top")
end

register_stairsplus_alias("stone")
register_stairsplus_alias("wood")
register_stairsplus_alias("cobble")
register_stairsplus_alias("brick")
register_stairsplus_alias("sandstone")
register_stairsplus_alias("glass")
register_stairsplus_alias("tree")
register_stairsplus_alias("jungletree")
register_stairsplus_alias("desert_stone")
register_stairsplus_alias("steelblock")
register_stairsplus_alias("mossycobble")
